### ISSUE TITLE
Failed to minify

### ISSUE THREAD

**Issue by ivawzh** [gmunguia/markdown-it-plantuml#1]
With `create-react-app` default `build` script, it tries to uglify the dependencies got the following error:

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/markdown-it-plantuml/lib/deflate.js:6

Read more here: http://bit.ly/2tRViJ9
```

**Comment by gmunguia** [comment]
Thanks for the feedback! The problem was I was using an es6 feature in deflate.js. Besides, deflate.js was using some undefined variables. I have published a patch to npm. Please, let me know if it works for you =).

Background: that dependency [deflate.js] is a really old implementation and was added as a workaround to keep the library compatible with planuml server, which uses an isomorphic inflate function on its side. I'm looking at deploying my own plantuml server in the long-term, so I did not want to invest time in fixing deflate.js.
