### ISSUE TITLE
enable setting server option from VS Code when used as extension by Markdown PDF extension

### ISSUE THREAD

**Issue by imuni4fun** [gmunguia/markdown-it-plantuml#12]
The example shows how to set options from javascript, but this is an awesome extension for VS Code using Markdown PDF extension.  It would be great to be able to set a setting for this extension so it could direct to a private PlantUML server.  I have to export to HTML, replace all URLs, and then print to PDF at the moment as a work around. In addition, the ability to strip the "/plantuml" from the url would be great.  This would allow easy use with plantuml docker images as shown in the following examples:

docker: docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat
currently generated: "http://www.plantuml.com/plantuml/svg/---sensitive---"
desired generated: "http://localhost:8080/svg/---sensitive---"

**Comment by FrVaBe** [comment]
I think this issue should be reported to the [vscode-markdown-pdf](https://github.com/yzane/vscode-markdown-pdf) project, because this is the plugin which uses _markdown-it-plantuml_ and needs to support the configuration of the _server_ option which is provided here.

Therefore I open a corresponding issue there [see #139](https://github.com/yzane/vscode-markdown-pdf/issues/139).

**Comment by gmunguia** [comment]
Closed as per the above.
