### ISSUE TITLE
Plans to support Ditaa

### ISSUE THREAD

**Issue by amedora** [gmunguia/markdown-it-plantuml#9]
Do you have any plans to support Ditaa diagram?
http://en.plantuml.com/ditaa

The PlanUML online server already supports '@startditaa' and that diagram.
[Example](http://www.plantuml.com/plantuml/uml/SoWkIImgISaiIKpaqjQ50cq51GLjE1kPmrMZ00NQO3cmHX3RJW4cKmDI4v9QKG9aefjJavAPc5wKc0jKuvAVN9gRcbTI0n9Mp4rCpqnM1B5Hp061wfJQ6YHXD3LWPn1mCwUL0YuGnyK9CyidlwHO8JzDeJo_A1jcEgUsBWQ06-kGcfS2zZy0)

**Comment by gmunguia** [comment]
You got it! 🎉

Check the [readme](https://github.com/gmunguia/markdown-it-plantuml#example-generating-ditaa-diagrams) for details and update to version 1.2.0 =)

Unfortunately, plantuml server fails when generating an svg image from ditaa diagrams ([bug report from 2016](http://forum.plantuml.net/4325/the-plantuml-server-raises-error-when-generating-svg-ditaa?show=4325#q4325)). I have added support for different image formats, so that you can at least generate a png image of your diagram.

Thanks for your suggestion!
